#ifndef SDLRECT_H
#define SDLRECT_H
#include "SDL2/SDL.h"
SDL_Rect g_rect;
SDL_Rect g_area;
SDL_Window* g_Window;
SDL_Renderer *g_renderer;
SDL_Surface *g_surface;
SDL_Texture *g_texture;
SDL_Event g_event;
#endif //SDLRECT_H